version: '3.3'

services:
    api:
        container_name: nestjs_api
        image: nestjs-api:1.0.0
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - assessment
        volumes:
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        restart: unless-stopped
    database:
        container_name: mongodb
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: assessment
        networks:
            - assessment
        volumes: 
            - /data/db

networks:
    assessment: