version: '3.3'

services:
    api:
        container_name: nestjs_api
        image: nestjs-api:1.0.0
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - assessment
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    assessment: